spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace/prac/petpy
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #                show_sql: true
        format_sql: true
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: true
logging.level:
  org.hibernate.SQL: debug
#    org.hibernate.type: trace